use std::process::Output;
use std::sync::Arc;

#[derive(Debug, Clone)]
pub enum Message {
    // --- Input changes ---
    NewMonitorInputChanged(String),
    ActuallySelected(String),
    StationMacInputChanged(String),
    // --- Button presses ---
    RefreshInterfaces,
    RefreshMonitorInterfaces,
    ActuallySelect,
    ChooseTargetAP,
    ListInterfaces,
    AddMonitor,
    DownInterface,
    UpInterface,
    KillNetworkServices,
    LiftNetworkServices,
    StartCollectingNetworkList,
    SelectAPFile,
    DeauthTarget,
    StartCapturing,
    SetPathToApFile(String),
    InterfaceSelected(Option<String>),
    MonitorSelected(Option<String>),
    DownInterfaceSelected(Option<String>),
    UpInterfaceSelected(Option<String>),
    CommandCompleted(Result<Output, Arc<std::io::Error>>),
    CrackCapturedHandshake,
    OpenSettings,
    CloseSettings,
    OpenStorageLocationDialog,
    SetStorageLocation(String),
    StorageLocationInputChanged(String),
    OpenRemoteServerCredentialsDialog,
    SetRemoteServerCredentials(String),
    RemoteServerCredentialsInputChanged(String),
    OpenLocalPasswordListDialog,
    SetLocalPasswordList(String),
    LocalPasswordListInputChanged(String),
    SaveSettings,
    CrackCaptureFileLocally,
    SetCapFilePathAndCrack(String),
}
