use std::process::Output;
use std::sync::Arc;

#[derive(Debug, Clone)]
pub enum Message {
    NewMonitorInputChanged(String),
    StationMacInputChanged(String),
    ListInterfaces,
    AddMonitor,
    DownInterface,
    UpInterface,
    KillNetworkServices,
    LiftNetworkServices,
    StartCollectingNetworkList,
    SelectAPFile,
    DeauthTarget,
    StartCapturing,
    SetPathToApFile(String),
    InterfaceSelected(Option<String>),
    MonitorSelected(Option<String>),
    DownInterfaceSelected(Option<String>),
    UpInterfaceSelected(Option<String>),
    CommandCompleted {
        label: String,
        external: bool,
        refresh_ifaces: bool,
        result: Result<Output, Arc<std::io::Error>>,
    },
    CrackCapturedHandshake,
    OpenSettings,
    CloseSettings,
    OpenStorageLocationDialog,
    SetStorageLocation(String),
    StorageLocationInputChanged(String),
    OpenRemoteServerCredentialsDialog,
    SetRemoteServerCredentials(String),
    RemoteServerCredentialsInputChanged(String),
    OpenLocalPasswordListDialog,
    SetLocalPasswordList(String),
    LocalPasswordListInputChanged(String),
    TerminalInputChanged(String),
    SaveSettings,
    CrackCaptureFileLocally,
    SetCapFilePathAndCrack(String),
    SelectApFromTable(usize),
    ToggleConsole,
    SortByColumn(usize),
    FilterTextChanged(String),
    TitleBarDrag,
    TitleBarDoubleClick,
    WindowMinimize,
    WindowToggleMaximize,
    WindowClose,
    DialogCancelled(String),
    SelectJob(u64),
    KillJob(u64),
    KillAllJobs,
    JobFinished {
        id: u64,
        result: Result<Option<i32>, String>,
    },
}
