use super::calllib::AP;
use iced::widget::Id;

// Define the application state
pub struct ConsoleApp {
    pub interfaces: Vec<String>,
    pub monitor_interfaces: Vec<String>,
    pub selected_interface: Option<String>,
    pub selected_monitor: Option<String>,
    pub selected_str: String,
    pub path_to_network: String,
    pub console_output: String,
    pub scrollable_id: Id,
    pub is_loading: bool,
    pub new_monitor_input: String,
    pub down_interface_input: String,
    pub up_interface_input: String,
    pub target_ap: AP,
    pub aps: Vec<AP>,
    pub path_to_csv_network: String,
    pub selected_n: usize,
    pub station_mac: String,
    pub network_services_killed: bool,
    pub show_settings: bool,
    pub settings_text: String,
    pub storage_location: String,
    pub storage_location_input: String,
    pub remote_server_credentials: String,
    pub remote_server_credentials_input: String,
    pub local_password_list: String,
    pub local_password_list_input: String,
    pub cap_file_path: String,
    pub show_console: bool,
    pub sort_column: usize,
    pub sort_descending: bool,
    pub filter_text: String,
}
