# AngrySniffer Configuration
[settings]
storage_location = "/root/.scans/"
remote_server_credentials = "/home/ker/samplemod/samplemod.sln"
local_password_list = "/home/ker/Downloads/10_million_password_list_top_1000000.txt"
